import { type NextPage } from "next";
import Head from "next/head";
import { signOut } from "next-auth/react";

import { useSession } from "next-auth/react"

const Home: NextPage = () => {
  const { data: session, status } = useSession();

  if (status === "loading") return <div>loading...</div>

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
        <h1 className="text-5xl font-extrabold leading-normal text-gray-700 md:text-[5rem]">
          Auth <span className="text-purple-300">T3</span> App
        </h1>
        {session?.user &&
          <p className="text-2xl text-gray-700">user: {session.user.email}</p>
        }
        <div className="flex divide-x">
          {!session ?
            <>
              <a href="/user/signin" className="px-3">Sign in</a>
              <a href="/user/signup" className="px-3">Sign up</a>
            </> :
            <button className="my-5" onClick={() => signOut()}>Logout</button>
          }
        </div>
      </main>
    </>
  );
};

export default Home;